CREATE TABLE IF NOT EXISTS GAME_INVENTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    STOCK INTEGER NOT NULL,
    GAME_INVENTORY_PRICE_ID BIGINT,
    FOREIGN KEY (GAME_INVENTORY_PRICE_ID) REFERENCES GAME_INVENTORY_PRICE(ID)
);

CREATE TABLE IF NOT EXISTS GAME_INVENTORY_PRICE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT,
    TYPE VARCHAR(255) NOT NULL,
    AMOUNT NUMERIC(38, 2) NOT NULL,
    CURRENCY VARCHAR(255) NOT NULL,
    GAME_INVENTORY_ID BIGINT NOT NULL,
    FOREIGN KEY (GAME_INVENTORY_ID) REFERENCES GAME_INVENTORY(ID)
);