CREATE TABLE IF NOT EXISTS GAME_INVENTORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    STOCK INTEGER NOT NULL,
    GAME_INVENTORY_PRICE_ID BIGINT,
    FOREIGN KEY (GAME_INVENTORY_PRICE_ID) REFERENCES GAME_INVENTORY_PRICE(ID)
);

CREATE TABLE IF NOT EXISTS GAME_INVENTORY_PRICE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT,
    TYPE VARCHAR(255) NOT NULL,
    AMOUNT NUMERIC(38, 2) NOT NULL,
    CURRENCY VARCHAR(255) NOT NULL,
    GAME_INVENTORY_ID BIGINT NOT NULL,
    FOREIGN KEY (GAME_INVENTORY_ID) REFERENCES GAME_INVENTORY(ID)
);

CREATE TABLE IF NOT EXISTS RENTAL (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    DATE DATETIME NOT NULL,
    CURRENCY VARCHAR(255) NOT NULL,
    PAYMENT_TYPE VARCHAR(255) NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES RENTAL_CUSTOMER_ENTITY(ID)
);

CREATE TABLE IF NOT EXISTS RENTAL_PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    TYPE VARCHAR(255) NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE DECIMAL(19, 2) NOT NULL,
    RENTAL_ID BIGINT NOT NULL,
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTAL(ID)
);

CREATE TABLE IF NOT EXISTS RENTAL_CUSTOMER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    VERSION BIGINT NOT NULL,
    FIRST_NAME VARCHAR(255) NOT NULL,
    LAST_NAME VARCHAR(255) NOT NULL,
    DOCUMENT_NUMBER VARCHAR(255) NOT NULL,
    LOYALTY_POINTS INT NOT NULL,
    RENTAL_ID BIGINT NOT NULL,
    FOREIGN KEY (RENTAL_ID) REFERENCES RENTAL(ID)
);
